### 创建数组

In [38]:
import numpy as np
import pandas as pd

#### 1.array

In [39]:
# numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
np.array([1, 2, 3, 4, 5])#numpy数组
np.array(pd.Series([1, 2, 3, '4']))#pandas的Series转为numpy的数组

array([1, 2, 3, '4'], dtype=object)

#### 2.linspace

In [ ]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
np.linspace(10, 100, 4, dtype = int)#指定左闭右闭取4个等差数列numpy数组

#### 3.arange

In [ ]:
# numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
np.arange(5)#从0开始的5个自然数的numpy数组
np.arange(1, 5)#从1开始左闭右开的自然数的numpy数组
np.arange(0, 10, 2)#左闭右开步长为2的数组

#### 4.uniform

In [ ]:
# numpy.random.uniform(low=0.0, high=1.0, size=None) 在上下限之间的均匀分布中生成随机样本
np.random.uniform(size = 5)
np.random.uniform()#0-1随机生成一个数
np.random.uniform(1, 5)
np.random.uniform(3, 4, size = (2, 3))

#### 5.random.randint

In [44]:
# numpy.random.randint(low, high=None, size=None, dtype=int)
np.random.randint(1, 100, 5)#在一个范围内生成n个随机整数样本。

array([83,  3, 26, 76, 42])

#### 6.random.random

In [49]:
# numpy.random.random(size=None)
np.random.random()#0-1之间的随机数
np.random.random(size =(2,3))

array([[0.71464835, 0.09462795, 0.57473184],
       [0.69464005, 0.78543202, 0.19550321]])

#### 7.logspace

In [62]:
# numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
# 在对数尺度上生成间隔均匀的数字 在 10^a 和 10^b（10 的 N 次幂）之间的 50 个对数间距点组成的行向量 y
np.logspace(1, 10, 3, base = 2, dtype = int)

array([   2,   45, 1024])

#### 8.zeros

In [65]:
# numpy.zeros(shape, dtype=float, order='C', *, like=None)
np.zeros((2,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

#### 9.ones

In [67]:
# numpy.ones(shape, dtype=None, order='C', *, like=None)
np.ones((3, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### 10.full

In [68]:
# numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)
np.full((3, 4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

#### 11.identity

In [69]:
# numpy.identity(n, dtype=None, *, like=None)
# 创建具有指定维度的单位矩阵。
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 数组操作

#### 12.min


In [74]:
# np.min(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
np.min([2, 3, 4, 5])
np.min((2, 3, 4))

2

#### 13.max

In [75]:
# np.max(a, axis=None,out=None)
np.max([2, 3, 4])

4


#### 14.unique


In [79]:
# numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None, *, equal_nan=True)
# 返回一个所有唯一元素排序的数组。
np.unique([1, 2, 2, 3, 4, 99, 88, 7, 7, 6, 66, 6, 5])#去重升序

array([ 1,  2,  3,  4,  5,  6,  7, 66, 88, 99])

#### 15.mean

In [80]:
# numpy.mean(a, axis=None, dtype=None, out=None)
np.mean([1, 2, 3, 4, 5])

3.0

#### 16.median

In [85]:
# numpy.median(a, axis=None, out=None) 中位数
np.median([1, 2, 3, 6, 6, 9])

4.5

#### 17.digitize


In [100]:
# numpy.digitize(x, bins, right=False)[source] right:表示该间隔是否包括右边或左边的bin。
# 返回输入数组中每个值所属的容器的索引
# 前一个数组的值在后一个数组值最先匹配到的位置
np.digitize([1, 2], [2, 2, 1])

array([2, 0], dtype=int64)


#### 18.reshape


In [109]:
# numpy.reshape(shap)
np.array([[1, 2, 3], [4, 5, 6]]).reshape((1, 6))
np.array([[1, 2, 3], [4, 5, 6]]).reshape((1, -1))
np.array([[1, 2, 3], [4, 5, 6]]).reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])


#### 19.expand_dims


In [122]:
# numpy.expand_dims(a, axis) 升维
np.expand_dims([1, 2, 3], 0)# 横向升维 最外面添一个括号
np.expand_dims([1, 2, 3], 1)# 纵向升维 纵向分别添加括号
np.expand_dims([[1,2],[3,4]], 0)
np.expand_dims([[1,2],[3,4]], 1)

array([[[1, 2],
        [3, 4]]])

#### 20.squeeze

In [125]:
# np.squeeze(a, axis=None) 降维 只能降一维的，降多维会丢失数据
np.squeeze([[2, 3]], 0)
np.squeeze([[2], [3]], 1)


array([2, 3])

#### 21.count_nonzero


In [131]:
# numpy.count_nonzero(a, axis=None, *, keepdims=False)
print(np.count_nonzero([0, 0, 1, 2, 0, 3]))
np.count_nonzero([[1, 2], \
                  [3, 4],\
                  [1, 0]], 0)#array([3, 2], dtype=int64) 第一列有3个不为0 第二列有2个不为0

3


array([3, 2], dtype=int64)


#### 22.argwhere


In [132]:
# numpy.argwhere(a) 查找并返回非零元素的所有下标
np.argwhere([0, 1, 2, 3, 0, 0])


array([[1],
       [2],
       [3]], dtype=int64)


#### 23.argmax&argmin


In [136]:
# numpy.argmax(a, axis=None, out=None, *, keepdims=<no value>)
print(np.argmin([0, -1, 1, 7]))
print(np.argmax([0, -1, 1, 7]))

1
3



#### 24.sot


In [145]:
# numpy.sort(a, axis=- 1, kind=None, order=None)
# kind:要使用的排序算法。{‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}
arr = np.array([9, 8, 7, 5, 6, 4, 2, 3, 1])
new_arr = np.sort(arr)
print(arr)
print(new_arr)

[9 8 7 5 6 4 2 3 1]
[1 2 3 4 5 6 7 8 9]



#### 25.abs


In [146]:
'''
numpy.absolute(x, /, out=None, *, where=True, casting='same_kind', 
               order='K', dtype=None, 
               subok=True[, signature, extobj]) = <ufunc 'absolute'>
'''
np.absolute(np.array([-1, -2, -3]))


array([1, 2, 3])


#### 26.round


In [148]:
# numpy.around(a, decimals=0, out=None) decimals:要保留的小数点的个数。
np.around([[0.83, 0.43, 0.67],[0.88, 0.45, -0.62]], 1)

array([[ 0.8,  0.4,  0.7],
       [ 0.9,  0.4, -0.6]])


#### 27.clip


In [152]:
# numpy.clip(a, a_min, a_max, out=None, **kwargs)
# 可以将数组的裁剪值保持在一个范围内。
np.clip(np.array([1, 2, 3, 4, 5]), 2, 3)

arr = np.array([1, 2, -1, -3, 5, 4])
arr.clip(0, 4)

array([1, 2, 0, 0, 4, 4])

### 替换数组中的值

#### 28.where


In [158]:
# numpy.where(condition, [x, y, ]/) 返回满足条件的数组元素
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr[np.where(arr > 3)]

arr2 = np.array([1, 2, 3, 4, 5, 6])
arr2[np.where(arr2 > 3)]

# 还可以用来替换pandas df中的元素
np.where(data[feature].isnull(), 1, 0)

NameError: name 'null' is not defined

#### 29.put


In [159]:
# numpy.put(a, ind, v) Ind:需要替换的索引 V:替换值
arr = np.array([1, 2, 3, 4, 5])
np.put(arr, 0, 100)
arr

array([100,   2,   3,   4,   5])

#### 30.copyto


In [163]:
# 将一个数组的内容复制到另一个数组中。
# numpy.copyto(dst, src, casting='same_kind', where=True)
arr = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.copyto(arr2, arr)
arr2

array([4, 5, 6])

### 集合操作

#### 31.查找公共元素


In [168]:
# numpy.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)
# 以排序的方式唯一的返回两个数组中所有公共的值
arr1 = np.array([1, 2, 1, 2, 3, 0])
arr2 = np.array([2, 3, 0, 0, 0])
arr3 = np.intersect1d(arr1, arr2)
arr3

array([0, 2, 3])

#### 32.查找不同元素


In [169]:
# numpy.setdiff1d(ar1, ar2, assume_unique=False)
arr4 = np.setdiff1d(arr1, arr2)
arr4

array([1])

#### 33.从两个数组中提取唯一元素


In [172]:
# numpy.setxor1d(ar1, ar2, assume_unique=False) 将按顺序返回两个数组中去共有去重所有唯一的值。
arr5 = np.setxor1d([1, 2, 3, 4, 7, 7, 6, 5], [7, 5, 5, 5])
arr5

array([1, 2, 3, 4, 6])

#### 34.合并


In [173]:
# numpy.union1d(ar1, ar2) 去重合并
np.union1d([1, 2, 2], [2, 3, 4])

array([1, 2, 3, 4])

### 数组分割

#### 35.水平分割


In [184]:
# numpy.hsplit(ary, indices_or_sections) 竖着切
a = np.array([[3, 4, 5], \
              [1, 2, 3]])
np.hsplit(a, 3)

[array([[3],
        [1]]),
 array([[4],
        [2]]),
 array([[5],
        [3]])]

#### 36.垂直分割


In [185]:
# numpy.vsplit(ary, indices_or_sections) 横着切
np.vsplit(a, 2)

[array([[3, 4, 5]]), array([[1, 2, 3]])]

### 数组叠加

#### 37.水平叠加


In [187]:
# numpy.hstack(tup) 将在另一个数组的末尾追加一个数组。
np.hstack(([2, 3, 2], [1, 1, 1]))

array([2, 3, 2, 1, 1, 1])

#### 38.垂直叠加


In [188]:
# numpy.vstack(tup)
np.vstack(([2, 3, 2], [1, 1, 1]))

array([[2, 3, 2],
       [1, 1, 1]])

### 数组比较


#### 39.allclose


In [193]:
# numpy.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
# 如果两个数组的形状相同，则Allclose函数根据公差值查找两个数组是否相等或近似相等。
np.allclose([1, 2, 3], [3, 4, 5]) # False
np.allclose([1, 1], [1, 1]) # True

a = np.array([0.25, 0.4, 0.6, 0.32])
b = np.array([0.26, 0.3, 0.7, 0.32])
 
tolerance = 0.1           ## Total Difference
print(np.allclose(a, b, tolerance))

 
tolerance = 0.5
print(np.allclose(a, b, tolerance))


False
True


#### 40.equal


In [197]:
'''
numpy.equal(x1, x2, /, out=None, *, 
            where=True, casting='same_kind', 
            order='K', dtype=None, subok=True[, signature, extobj]
           ) = <ufunc 'equal'>
'''
# 它比较两个数组的每个元素，如果元素匹配就返回True。
np.equal([1, 1, 3], [2, 1, 4]) 

array([False,  True, False])

### 重复的数组元素


#### 41.repeat


In [201]:
# numpy.repeat(a, repeats, axis=None)
# 用于重复数组中的元素n次。
np.repeat([1, 2, 3], 3)
np.repeat([[1, 2], [3, 4]], 2)

fruits = pd.DataFrame([
  ['Mango',40],
  ['Apple',90],
  ['Banana',130]
],columns=['Product','ContainerSales'])
fruits
fruits['year'] = np.repeat(2023, fruits.shape[0])
fruits

Product  ContainerSales  year
0   Mango              40  2023
1   Apple              90  2023
2  Banana             130  2023

#### 42.tile


In [204]:
# numpy.title(A, reps) 通过重复A，reps次来构造一个数组
np.tile('Rong', 5)

np.tile(3, (2, 3))

array([[3, 3, 3],
       [3, 3, 3]])

### 爱因斯坦求和


#### 43.einsum


In [211]:
'''
umpy.einsum(subscripts, *operands, out=None, 
            dtype=None, order='K', 
            casting='safe', optimize=False)
用于计算数组上的多维和线性代数运算。
'''
a = np.arange(1,10).reshape(3,3)
b = np.arange(21,30).reshape(3,3)
print(a)
print(b)
print('取a对角线\n', np.einsum('ii->i',a))
print('a的转置\n', np.einsum('ji',a))
print('ab矩阵相乘\n', np.einsum('ij, jk', a, b))  
print('a的迹\n', np.einsum('ii',a))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[21 22 23]
 [24 25 26]
 [27 28 29]]
取a对角线
 [1 5 9]
a的转置
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
ab矩阵相乘
 [[150 156 162]
 [366 381 396]
 [582 606 630]]
a的迹
 15


### 统计分析


#### 44.直方图

In [213]:
# numpy.histogram(a, bins=10, range=None, normed=None, weights=None, density=None)
# 统计分析函数，可计算一组数据的直方图值。
np.histogram([[3, 4, 5, 2], [6, 7, 2, 6]])

(array([2, 0, 1, 0, 1, 0, 1, 0, 2, 1], dtype=int64),
 array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ]))

#### 45.百分位数


In [229]:
'''
numpy.percentile(a, q, axis=None, out=None, 
                 overwrite_input=False, method='linear', 
                 keepdims=False, *, 
                 interpolation=None)[source]
沿指定轴计算数据的Q-T-T百分位数
a:输入。
q:要计算的百分位。
overwrite_input:如果为true 则允许输入数组修改中间计算以节省内存。
'''
# 将一组含有n个值的数据，按数值从小到大排列，将处于p%位置的值称第 p 百分位数。
print(np.percentile([1, 2, 3, 5], 25))

1.75


#### 46.标准偏差


In [232]:
'''
numpy.std(a, axis=None, dtype=None, out=None, 
          ddof=0, keepdims=<no value>, *, 
          where=<no value>)
'''
# std用于计算沿轴的标准偏差
a = np.array([[2, 4, 6], [4, 8, 12]])
print(np.std(a, axis = 1))
print(np.std(a, axis = 0))

[1.63299316 3.26598632]
[1. 2. 3.]


#### 47.方差


In [234]:
'''
numpy.var(a, axis=None, dtype=None, out=None, 
          ddof=0, keepdims=<no value>, *, 
          where=<no value>)
'''
print(np.var(a, axis = 1))
print(np.var(a, axis = 0))

[ 2.66666667 10.66666667]
[1. 4. 9.]


### 数组打印


#### 48.显示带有两个十进制值的浮点数


In [240]:
'''
numpy.set_printoptions(precision=None, threshold=None, edgeitems=None, 
                       linewidth=None, suppress=None, nanstr=None, infstr=None, 
                       formatter=None, sign=None, floatmode=None, *,
                       legacy=None)
'''
np.set_printoptions(precision = 3)#保留3位小数点
a = np.array([12.1234, 13.4567])
a

array([12.123, 13.457])

### 保存和加载数据


#### 49.保存


In [245]:
'''
numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', 
              newline='\n', header='', footer='', 
              comments='# ', encoding=None)
'''
arr = np.linspace(10, 100, 49).reshape(7, 7)
np.savetxt('array.txt', arr)

#### 50.加载

In [247]:
'''
numpy.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None,
              converters=None, skiprows=0, usecols=None, unpack=False, 
              ndmin=0, encoding='bytes', max_rows=None, *, 
              quotechar=None, like=None)
'''
np.loadtxt('array.txt')

array([[ 10.   ,  11.875,  13.75 ,  15.625,  17.5  ,  19.375,  21.25 ],
       [ 23.125,  25.   ,  26.875,  28.75 ,  30.625,  32.5  ,  34.375],
       [ 36.25 ,  38.125,  40.   ,  41.875,  43.75 ,  45.625,  47.5  ],
       [ 49.375,  51.25 ,  53.125,  55.   ,  56.875,  58.75 ,  60.625],
       [ 62.5  ,  64.375,  66.25 ,  68.125,  70.   ,  71.875,  73.75 ],
       [ 75.625,  77.5  ,  79.375,  81.25 ,  83.125,  85.   ,  86.875],
       [ 88.75 ,  90.625,  92.5  ,  94.375,  96.25 ,  98.125, 100.   ]])