### 创建数组

In [38]:
import numpy as np
import pandas as pd

#### 1.array

In [39]:
# numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
np.array([1, 2, 3, 4, 5])#numpy数组
np.array(pd.Series([1, 2, 3, '4']))#pandas的Series转为numpy的数组

array([1, 2, 3, '4'], dtype=object)

#### 2.linspace

In [ ]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
np.linspace(10, 100, 4, dtype = int)#指定左闭右闭取4个等差数列numpy数组

#### 3.arange

In [ ]:
# numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
np.arange(5)#从0开始的5个自然数的numpy数组
np.arange(1, 5)#从1开始左闭右开的自然数的numpy数组
np.arange(0, 10, 2)#左闭右开步长为2的数组

#### 4.uniform

In [ ]:
# numpy.random.uniform(low=0.0, high=1.0, size=None) 在上下限之间的均匀分布中生成随机样本
np.random.uniform(size = 5)
np.random.uniform()#0-1随机生成一个数
np.random.uniform(1, 5)
np.random.uniform(3, 4, size = (2, 3))

#### 5.random.randint

In [44]:
# numpy.random.randint(low, high=None, size=None, dtype=int)
np.random.randint(1, 100, 5)#在一个范围内生成n个随机整数样本。

array([83,  3, 26, 76, 42])

#### 6.random.random

In [49]:
# numpy.random.random(size=None)
np.random.random()#0-1之间的随机数
np.random.random(size =(2,3))

array([[0.71464835, 0.09462795, 0.57473184],
       [0.69464005, 0.78543202, 0.19550321]])

#### 7.logspace

In [62]:
# numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
# 在对数尺度上生成间隔均匀的数字 在 10^a 和 10^b（10 的 N 次幂）之间的 50 个对数间距点组成的行向量 y
np.logspace(1, 10, 3, base = 2, dtype = int)

array([   2,   45, 1024])

#### 8.zeros

In [65]:
# numpy.zeros(shape, dtype=float, order='C', *, like=None)
np.zeros((2,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

#### 9.ones

In [67]:
# numpy.ones(shape, dtype=None, order='C', *, like=None)
np.ones((3, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### 10.full

In [68]:
# numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)
np.full((3, 4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

#### 11.identity

In [69]:
# numpy.identity(n, dtype=None, *, like=None)
# 创建具有指定维度的单位矩阵。
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 数组操作

#### 12.min


In [74]:
# np.min(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
np.min([2, 3, 4, 5])
np.min((2, 3, 4))

2

#### 13.max

In [75]:
# np.max(a, axis=None,out=None)
np.max([2, 3, 4])

4


#### 14.unique


In [79]:
# numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None, *, equal_nan=True)
# 返回一个所有唯一元素排序的数组。
np.unique([1, 2, 2, 3, 4, 99, 88, 7, 7, 6, 66, 6, 5])#去重升序

array([ 1,  2,  3,  4,  5,  6,  7, 66, 88, 99])

#### 15.mean

In [80]:
# numpy.mean(a, axis=None, dtype=None, out=None)
np.mean([1, 2, 3, 4, 5])

3.0

#### 16.median

In [85]:
# numpy.median(a, axis=None, out=None) 中位数
np.median([1, 2, 3, 6, 6, 9])

4.5

#### 17.digitize


In [100]:
# numpy.digitize(x, bins, right=False)[source] right:表示该间隔是否包括右边或左边的bin。
# 返回输入数组中每个值所属的容器的索引
# 前一个数组的值在后一个数组值最先匹配到的位置
np.digitize([1, 2], [2, 2, 1])

array([2, 0], dtype=int64)


#### 18.reshape


In [109]:
# numpy.reshape(shap)
np.array([[1, 2, 3], [4, 5, 6]]).reshape((1, 6))
np.array([[1, 2, 3], [4, 5, 6]]).reshape((1, -1))
np.array([[1, 2, 3], [4, 5, 6]]).reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])


#### 19.expand_dims


In [122]:
# numpy.expand_dims(a, axis) 升维
np.expand_dims([1, 2, 3], 0)# 横向升维 最外面添一个括号
np.expand_dims([1, 2, 3], 1)# 纵向升维 纵向分别添加括号
np.expand_dims([[1,2],[3,4]], 0)
np.expand_dims([[1,2],[3,4]], 1)

array([[[1, 2],
        [3, 4]]])

#### 20.squeeze

In [125]:
# np.squeeze(a, axis=None) 降维 只能降一维的，降多维会丢失数据
np.squeeze([[2, 3]], 0)
np.squeeze([[2], [3]], 1)


array([2, 3])

#### 21.count_nonzero


In [131]:
# numpy.count_nonzero(a, axis=None, *, keepdims=False)
print(np.count_nonzero([0, 0, 1, 2, 0, 3]))
np.count_nonzero([[1, 2], \
                  [3, 4],\
                  [1, 0]], 0)#array([3, 2], dtype=int64) 第一列有3个不为0 第二列有2个不为0

3


array([3, 2], dtype=int64)


#### 22.argwhere


In [ ]:
# numpy.argwhere(a)


#### 23.argmax&argmin


In [ ]:
# numpy.argmax(a, axis=None, out=None, *, keepdims=<no value>)



#### 24.sot


In [ ]:
# numpy.sort(a, axis=- 1, kind=None, order=None)


#### 25.abs


In [ ]:
'''
numpy.absolute(x, /, out=None, *, where=True, casting='same_kind', 
               order='K', dtype=None, 
               subok=True[, signature, extobj]) = <ufunc 'absolute'>
'''




#### 26.round


In [ ]:
# numpy.around(a, decimals=0, out=None)



#### 27.cip


In [ ]:
# numpy.clip(a, a_min, a_max, out=None, **kwargs)


### 替换数组中的值

#### 28.where


In [ ]:
# numpy.where(condition, [x, y, ]/)

#### 29.put


In [ ]:
# numpy.put(a, ind, v)

#### 30.copyto


In [ ]:
# 

### 集合操作

#### 31.查找公共元素


In [ ]:
# 

#### 32.查找不同元素


In [ ]:
# 

#### 33.从两个数组中提取唯一元素


In [ ]:
# 

#### 34.合并


In [ ]:
# 

### 数组分割

#### 35.水平分割


In [ ]:
# 

#### 36.垂直分割


In [ ]:
# 

### 数组叠加

#### 37.水平叠加


In [ ]:
# 

#### 38.垂直叠加


In [ ]:
# 

### 数组比较


#### 39.allclose


In [ ]:
# 

#### 40.equal


In [ ]:
# 

### 重复的数组元素


#### 41.repeat


In [ ]:
# 

#### 42.tile


In [ ]:
# 

### 爱因斯坦求和


#### 43.einsum


In [ ]:
# 

### 统计分析


#### 44.直方图


In [ ]:
# 

#### 45.百分位数


In [ ]:
# 

#### 46.标准偏差


In [ ]:
# 

#### 47.方差


In [ ]:
# 

### 数组打印


#### 48.显示带有两个十进制值的浮点数


In [ ]:
# 

### 保存和加载数据


#### 49.保存


In [ ]:
# 

#### 50.加载

In [ ]:
# 