## pytorch常用函数

>> https://blog.csdn.net/qq_37085158/article/details/124617128?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522168100310916800227462728%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=168100310916800227462728&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~top_positive~default-1-124617128-null-null.142%5Ev82%5Econtrol,201%5Ev4%5Eadd_ask,239%5Ev2%5Einsert_chatgpt&utm_term=pytorch%E5%B8%B8%E7%94%A8%E5%87%BD%E6%95%B0&spm=1018.2226.3001.4187


In [7]:
import torch

### 张量 tensor

#### is_tensor


In [8]:
# obj是一个tensor，则返回True
print(torch.is_tensor([1, 2])) #False
torch.is_tensor(torch.Tensor(1,2)) #True

False


True

#### is_storage

Storage类型是pytorch中的一个类型，它与tensor是对应的。

tensor分为头信息区(Tensor)和存储区(Storage)

In [12]:
a = torch.rand(2, 3)
print(torch.is_storage(a)) #False
print(torch.is_storage(a.storage())) #True

False
True


C:\Users\admin\AppData\Local\Temp\ipykernel_17720\1141974329.py:3: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(torch.is_storage(a.storage()))


#### numel

元素个数

In [13]:
torch.numel(a)

6

### 创建操作

#### eye

返回一个2维张量，对角线为1，其它位置为0。

n (int) 行数

m (int, optional) 列数，如果为None，则默认为n

out (Tensor, optional)

In [16]:
# 单位矩阵
torch.eye(3, dtype = int)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

#### Tensor

In [23]:
a = torch.Tensor([1, 2, 3, 4, 5])#单精度浮点型张量
print(a)
print(a.type())

tensor([1., 2., 3., 4., 5.])
torch.FloatTensor


#### tensor

In [25]:
b = torch.tensor([0, 1, 2, 3, 4])#长整型张量
print(b)
print(b.type())

tensor([0, 1, 2, 3, 4])
torch.LongTensor


In [26]:
# 指定类型
c = torch.tensor([1, 2, 3], dtype=torch.double)
c.type()

'torch.DoubleTensor'

#### from_numpy

将numpy.ndarray转换为Tensor。

返回的张量tensor和ndarray共享同一内存空间，

修改一个会导致另一个也被修改，返回的张量不能改变大小。

In [28]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = torch.from_numpy(a)
print(a)
print(b)
a[0] = 9
print(a)
print(b)

[1 2 3 4]
tensor([1, 2, 3, 4], dtype=torch.int32)
[9 2 3 4]
tensor([9, 2, 3, 4], dtype=torch.int32)


#### linspace

返回一个1维张量，包含在start和end上均匀间隔的steps个点。

start (float) -序列起点
end (float) - 序列终点
steps (int) - 在start与end间生成的样本数
out (Tensor, optional) - 结果张量

In [29]:
torch.linspace(1, 10, 5)#等差数列

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

#### logspace

创建对数均分的1维张量。返回一个1维张量，包含在区间base^{start}base 
start
 和base^{end}base 
end
 上以对数刻度均匀间隔的steps个点。
注意事项：长度为steps，底为base

start: 数列起始值
end: 数列结束值
steps: 数列长度
base: 对数函数的底，默认为10


In [30]:
torch.logspace(1, 10, 3)

tensor([1.0000e+01, 3.1623e+05, 1.0000e+10])

#### ones

In [32]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

#### ones_like

In [36]:
torch.ones_like(torch.tensor([[1, 2], [3, 4]]))

tensor([[1, 1],
        [1, 1]])

#### rand

In [40]:
torch.rand(10)#从区间(0, 1)的均匀分布中抽取的一组随机数，形状由可变参数sizes定义
torch.rand(2, 3)

tensor([[0.9762, 0.7039, 0.0255],
        [0.6920, 0.2084, 0.8887]])

#### randn

In [41]:
# 标准正态分布(mean=0, std=1)中抽取一组随机数
torch.randn(3, 4)

tensor([[ 0.4512,  0.3959, -2.0420, -0.3465],
        [-1.1788, -1.6449,  0.5853,  1.5284],
        [-0.0711, -0.2836,  1.1496, -1.1614]])

#### randperm

In [46]:
torch.randperm(4)#n以内的数(不包括n)随机排列

tensor([1, 3, 2, 0])

#### arange

In [48]:
# torch.arange(start, end, step=1, out=None)
torch.arange(0, 9)# start到end-1的正序排列

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

#### range

In [49]:
# 推荐使用torch.arange()，因为torch.arange()兼容更多种类的参数
torch.range(0, 9)#包含右边界

C:\Users\admin\AppData\Local\Temp\ipykernel_17720\2843270517.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 9)


tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### zeros

In [50]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### zeros_like

In [54]:
ten = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch.zeros_like(ten)

tensor([[0, 0, 0],
        [0, 0, 0]])

#### empty_like

In [55]:
torch.empty_like(ten)

tensor([[0, 0, 0],
        [0, 0, 0]])

#### as_strided

此方法根据现有tensor以及给定的步长来创建一个视图（类型仍然为tensor）。

torch.as_strided(input, size, stride, storage_offset=0)—>Tensor

视图是指创建一个方便查看的东西，与原数据共享内存，它并不占用内存，也不存储数据，只是将原有的数据进行整理，显示其中部分内容或者进行重排序后显示出来

- input：此参数指定了在哪个数据上创建视图，input需为tensor。
- size：指定了生成的视图的大小，需要为一个矩阵（当然此矩阵大小可以大于原矩阵，但是也有限制），可以是tensor或者list等等。
- stride：输出tensor的步长，根据原矩阵和步长生成了新矩阵。
- storage_offset：输出张量的基础存储中的偏移量。

总结：stride是指定步长，其中行从原数据第0个数据开始，而列从视图中行的第0个数据开始。将整个数组整合为1维数组后按步长进行寻找。

In [92]:
torch.manual_seed(0) #随机种子 使得训列结果得以复现
a = torch.rand(4, 4)
# b是a的视图,用的是a的数据 修改一个另一个也随之修改
#将原矩阵平铺成一维矩阵.第一个数默认是第一个,然后根据(i,j) i下一行走几步, j下一列走几步
b = torch.as_strided(a, (3, 3), (1, 3))
print(a)
print(b)
print()
b = torch.as_strided(a, (3, 3), (1, 1), 4)# 4指的是索引4的数
print(a)
print(b)


tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939, 0.5185]])
tensor([[0.4963, 0.1320, 0.4901],
        [0.7682, 0.3074, 0.8964],
        [0.0885, 0.6341, 0.4556]])

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939, 0.5185]])
tensor([[0.3074, 0.6341, 0.4901],
        [0.6341, 0.4901, 0.8964],
        [0.4901, 0.8964, 0.4556]])


#### empty_strided

创建一个使用未初始化值填满的tensor，然后返回创建tensor的视图

In [105]:
# torch.empty_strided(size, stride, *, dtype=None, layout=None, device=None, requires_grad=False, pin_memory=False)
#  → Tensor
# 此方法相当于torch.empty(size).as_strided(size, stride)，也就是包含了两个方法，
# 先创建empty的tensor，再创建在此tensor上的视图。
torch.empty_strided((3, 3), (0, 0))


tensor([[3.5873e-43, 3.5873e-43, 3.5873e-43],
        [3.5873e-43, 3.5873e-43, 3.5873e-43],
        [3.5873e-43, 3.5873e-43, 3.5873e-43]])

#### full

In [106]:
# 给定一个值fill_value和一个size，创建一个矩阵元素全为fill_value的大小为size的tensor。
# torch.full(size, fill_value, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
torch.full((3, 2), 5)

tensor([[5, 5],
        [5, 5],
        [5, 5]])

#### full_like

In [109]:
# 将input的形状作为返回结果tensor的形状，其他形如torch.full()。
# torch.full_like(input, fill_value, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format) → Tensor
torch.full_like(ten, 4)

tensor([[4, 4, 4],
        [4, 4, 4]])

#### sparse_coo_tensor

In [110]:
# 创建一个Coordinate(COO) 格式的稀疏矩阵，返回值是一个tensor。
# torch.sparse_coo_tensor(indices, values, size=None, dtype=None, device=None, requires_grad=False)
# indices：此参数是指定非零元素所在的位置
# values：此参数指定了非零元素的值
# size：指定了稀疏矩阵的大小
# dtype：指定返回tensor中数据的类型
# device：指定创建的tensor在cpu还是cuda上
# requires_grad：指定创建的tensor需不需要梯度信息，默认为False
indice = torch.tensor([[0, 1, 1], [2, 0, 2]])
values = torch.tensor([1, 2, 3])
torch.sparse_coo_tensor(indice, values, [2, 4])



tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([1, 2, 3]),
       size=(2, 4), nnz=3, layout=torch.sparse_coo)

#### as_tensor

In [113]:
# 将数据转化为tensor，这些数据可以是（list, tuple, NumPy ndarray, scalar, and other types）等等
# data：tensor的初始化数据。可以是 list, tuple, NumPy ndarray, scalar, and other types
# dtype：tensor中数据的类型，如果不指定则使用data中的数据类型
# device：指定了返回tensor所在的位置（cpu或者cuda），如果没有指定则使用当前默认设备，一般是cpu，当然也可以使用前面讲过的torch.set_default_tensor_type()来更改默认设置
a = [1, 2, 3]
b = torch.as_tensor(a)
a[0] = 9
b

tensor([1, 2, 3])

### 索引|切片|连接|换位

#### cat

In [118]:
# 在给定维度上对输入的张量序列seq进行连接操作
# 第一个参数tensors是你想要连接的若干个张量，按你所传入的顺序进行连接，
# 注意每一个张量需要形状相同，或者更准确的说，进行行连接的张量要求列数相同，进行列连接的张量要求行数相同。
# 第二个参数dim表示维度，dim=0则表示按行连接，dim=1表示按列连接
torch.cat((torch.tensor([1, 2, 3]), torch.tensor([1, 2, 3, 4])), 0)# tensor([1, 2, 3, 1, 2, 3, 4])
torch.cat((torch.tensor([[1, 2, 3]]), torch.tensor([[1, 2, 3]])), 0)

tensor([[1, 2, 3],
        [1, 2, 3]])

#### chunk

In [123]:
# 拆分张量:把一个tensor均匀分割成若干个小tensor，在给定维度上将输入张量进行分块。
# torch.chunk(tensor, chunks, dim=0)
torch.arange(11).chunk(2)

(tensor([0, 1, 2, 3, 4, 5]), tensor([ 6,  7,  8,  9, 10]))

#### gather

In [138]:
# 沿给定轴dim，将输入索引张量index指定位置的值进行聚合
# torch.gather(input, dim, index, out=None)
# input(Tensor) - 源张量
# dim(int) - 索引的轴
# index(LongTensor) - 聚合元素的下标
# out - 目标张量
t1 = torch.Tensor([[2, 5],\
                   [4, 7]])
index = torch.LongTensor([[0, 1]])
t2 = torch.gather(t1, 0, index) #tensor([[2., 7.]])
t2 = torch.gather(t1, 1, index) #tensor([[2., 5.]])
index = torch.LongTensor([[0], [1]])
t2 = torch.gather(t1, 1, index) #tensor([[2.], [7.]])
t2

tensor([[2.],
        [7.]])

#### index_select

#### masked_select

#### nonzero

#### split

#### squeeze

#### unsequeeze

#### stack

#### t

#### transpose

#### unbind

#### where

### 随机抽样 Random sampling

#### manual_seed

#### initial_seed

#### get_rng_state

#### set_rng_state

#### default_generator

#### bernoulli

#### multinomial

#### normal

#### rand

#### rand_like

#### randint

#### randint_like

#### randn

#### randn_like

#### randperm

### 序列化 Serialization

#### save

#### load

### 并行化 Parallelism

#### get_num_threads

#### set_num_threads

### 数学操作 Math operations

#### abs

#### acos

#### add

#### addcdiv

#### addcmul

#### asin

#### atan

#### atan2

#### ceil

#### clamp

#### cos

#### cosh

#### div

#### exp

#### floor

#### fmod

#### frac

#### lerp

#### log

#### log1p

#### mul

#### neg

#### pow

#### reciprocal

#### remainder

#### round

#### rsqrt

#### sigmoid

#### sign

#### sin

#### sinh

#### sqrt

#### tan

#### tanh

#### trunc

#### cumprod

#### cumsum

#### dist

#### mean

#### median

#### mode

#### norm

#### prod

#### std

#### sum

var

#### 比较操作

#### eq

#### equal

#### ge

#### gt

#### kthvalue

#### le

#### lt

#### max

#### min

#### ne

#### sort

#### topk

#### cross

#### diag

#### histc

#### renorm

#### trace

#### tril

#### triu

#### dot

#### eig

#### inverse

#### mm

#### mv

### 其他

#### any

#### all